### PR TITLE
Added fix for basic relative URLs in servers

### PR DESCRIPTION
**Pull request by dipsmishra**
This adds support for basic relative URLs in servers
**Note**: this still does not support variables/variable substitutions in URLs

### CODE REVIEW

**Comment by dipsmishra** [comment]
This resolves #59

**Comment by dipsmishra** [comment]
@kobik @kibertoad @tamlyn 

Can one of you please review and merge if it looks good?
Thank you!

**Comment by deepakmonga2408** [comment]
Any update on this fix? This PR resolves the relative path errors and all tests pass. It would be great if you can review, merge and release.

**Comment by kobik** [comment]
Hi @dipsmishra,

Thanks for the PR!

I hope I'll have the time to look on the nezt couple of days.

**Review by kobik — APPROVED** [review]
Thanks @dipsmishra !

**Comment by kobik** [comment]
@dipsmishra can you please update CHANGELOG.md?

**Comment by dipsmishra** [comment]
> @dipsmishra can you please update CHANGELOG.md?

Yes, sure. Should I update the version in package.json to 2.0.5 too? I am not entirely sure about your release process and hence, checking.

**Comment by kobik** [comment]
No need to update the json file as I use 'npm version' command for bumping and tagging  before publishing it

**Comment by dipsmishra** [comment]
Thanks for the clarification, @kobik - I have updated the PR accordingly and also pulled in the latest changes from 'master' to get it ready for merge.

**Comment by deepakmonga2408** [comment]
@kobik, Can you please review and merge this PR?

**Comment by dipsmishra** [comment]
@kobik, Is there anything else needed to get this PR merged? Please let me know.

**Comment by kibertoad** [comment]
CI is currently misconfigured for the repo.
@kobik Could you please either drop travis and enable CircleCI for this repo (on their end, GitHub side is correct, I believe), or give me admin permissions for the repo so that I could do so?

**Comment by kobik** [comment]
@dipsmishra should be fixed now

**Comment by kibertoad** [comment]
@kobik 
```
> api-schema-builder@2.0.4 coveralls /root/project
> cat ./coverage/lcov.info |./node_modules/.bin/coveralls


/root/project/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Any ideas?
Wonder if we should disable coverage reporting for now to unblock the PR.

**Comment by kobik** [comment]
fixed according to this https://github.com/lemurheavy/coveralls-public/issues/632.

i don't like it too much as i was also required that it would allowed also in PR in order to work here.

**Comment by deepakmonga2408** [comment]
@kobik any updated on pushing this PR through?

**Comment by kibertoad** [comment]
Thank you!

**Pull request merged**
